config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#home'

  resources :products do
    resources :product_orders, only: [ :create, :destroy ]
    member do
      post 'save_item', to: 'products#save_item'
    end
  end

  resources :orders, only: [ :index, :show, :edit, :update, :destroy ] do
    get 'basket', to: 'orders#basket'
    get 'checkout', to: 'orders#checkout'
    get 'confirmation_page', to: 'orders#confirmation_page'
  end

  resources :product_orders, only: [:destroy]

  get 'my_account', to: 'orders#my_account'
  get 'reviews', to: 'orders#reviews'
  get 'sale_items', to: 'orders#sale_items'
  get 'saved_items', to: 'products#saved_items'

  resources :users, only: [ :show ] do
    resources :reviews, only: [ :new, :create, :show ]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    © BuyBaby
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light bg-light navbar-lewagon sticky-top">
  <div class="d-flex flex-row">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  <h3 class="mt-1">Buy</h3>
  <h3 class="mt-1" style="color: #9CF6F6">Ba</h3>
  <h3 class="mt-1" style="color: #FFE357">by</h3>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse mt-2" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Explore", products_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Sell An Item", new_product_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Saved Items", saved_items_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= form_tag products_path, method: :get do %>
          <div class="input-group">
            <%= text_field_tag :query,
              params[:query],
              class: "input",
              aria: { label: "find", describedby: "basic-addon1" }
            %>
            <i class="fas exp fa-search"></i>
          </div>
        <% end %>
      </li>
      <li>
        <% if current_user.present? %>
          <% if current_user.orders.find_by(state:"pending").present? %>
            <%= link_to edit_order_path(current_user.orders.find_by(state:"pending")) do %>
              <i class="fas fa-shopping-cart"></i>
            <% end %>
            <% unless current_user.orders.find_by(state:"pending").product_orders.count.zero? %>
            <div class='badge badge-warning' id='lblCartCount'>
              <span id="cartCount"><%= current_user.orders.find_by(state:"pending").product_orders.count %></span>
            </div>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to my_account_path do %>
            <i class="fas fa-shopping-cart"></i>
          <% end %>
        <% end %>
      </li>
      <li class="nav-item dropdown ml-3">
        <% if user_signed_in? %>
          <%= image_tag "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1647&q=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right p-3" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <%= current_user.email %>
            <%= link_to "My Account", my_account_path, class: "dropdown-item" %>
            <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class: "dropdown-item" %>
          <% else %>
            <%= link_to 'Sign in', new_user_session_path, class: "dropdown-item" %>
            <%= link_to 'Sign up', new_user_registration_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>