config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#home'

  resources :products do
    resources :product_orders, only: [ :create, :destroy ]
    member do
      post 'save_item', to: 'products#save_item'
    end
  end

  resources :orders, only: [ :index, :show, :edit, :update, :destroy ] do
    get 'basket', to: 'orders#basket'
    get 'checkout', to: 'orders#checkout'
    get 'confirmation_page', to: 'orders#confirmation_page'
  end

  resources :product_orders, only: [:destroy]

  get 'my_account', to: 'orders#my_account'
  get 'reviews', to: 'orders#reviews'
  get 'sale_items', to: 'orders#sale_items'
  get 'saved_items', to: 'products#saved_items'

  resources :users, only: [ :show ] do
    resources :reviews, only: [ :new, :create, :show ]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :product_orders, dependent: :destroy
  has_many :products, through: :product_orders, dependent: :destroy

  monetize :amount_cents

  def total_price
    product_orders.map { |item| item.product.price_cents }.sum
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = policy_scope(Order)
  end

  def my_account
    @products = policy_scope(Product)
    @orders = Order.where(user: current_user)
    @featured_products = @products.all.sample(3)
    authorize @orders
  end

  def checkout
    @order = Order.find(params[:order_id])
    authorize @order
  end

  def confirmation_page
    @order = Order.find(params[:order_id])
    authorize @order
  end

  def reviews
    @products = policy_scope(Product)
    @user = current_user
    @orders = Order.where(user: current_user)
    authorize @orders
  end

  def sale_items
    @products = policy_scope(Product)
    @user = current_user
    @orders = Order.where(user: current_user)
    authorize @orders
  end

  def show; end

  def edit
    @products = @order.products
    @users = @products.map { |product| product.user }.uniq
    @similar_products = @users.map { |user| user.products }.flatten - @products
  end

  def update
    @order.update(order_params)
    Order.create user: current_user, state: "pending"
    redirect_to order_confirmation_page_path(@order)
  end

  def destroy
    @order.destroy
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:state, :user, :product, :delivery_option, :payment_option)
  end

  def set_order
    @order = Order.find(params[:id])
    authorize @order
  end
end

app/views/orders/checkout.html.erb
<div class="container">
  <div class="mt-2 py-4 text-center">
    <h1>Checkout</h1>
  </div>
  <div class="row">
    <div class="col-md-4 order-md-2 mb-4">
      <div class="sticky-basket">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">Your Basket</span>
          <span class="badge badge-secondary badge-pill"><%= current_user.orders.find_by(state:"pending").product_orders.count %></span>
        </h4>
        <% @order.product_orders.each do |item| %>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex lh-condensed">
            <% item.product.photos.each_with_index do |photo, index| %>
              <%= cl_image_tag photo.key, height: 100, width: 100, crop: :fill, gravity: :center %>
            <% end %>
            <div class="col-6 pl-2">
              <h6 class="my-0"><%= item.product.name %></h6>
              <small class="text-muted"><%= item.product.description %></small>
              <small class="text-muted">Sale type: <%= item.product.sale_type %></small>
            </div>
            <div class="col-1">
              <span class="text-muted">£<%= item.product.price_cents %></span>
            </div>
          </li>
          <% end %>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (GBP)</span>
            <strong><h6>£<%= @order.total_price %></h6></strong>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-8 order-md-1">
      <h4 class="mb-3">Billing address</h4>
      <form class="needs-validation" novalidate="">
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="firstName">First name</label>
            <input type="text" class="form-control" id="firstName" placeholder="Name" value="" required="">
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="lastName">Last name</label>
            <input type="text" class="form-control" id="lastName" placeholder="Surname" value="" required="">
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>
        <div class="mb-3">
          <label for="address">Address</label>
          <input type="text" class="form-control" id="address" placeholder="First line of address" required="">
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 mb-3">
            <label for="city">City</label>
            <select class="custom-select d-block w-100" id="city" required="">
              <option value="">Choose...</option>
              <option>London</option>
            </select>
            <div class="invalid-feedback">
              Please provide a valid city.
            </div>
          </div>
          <div class="col-md-5 mb-3">
            <label for="country">Country</label>
            <select class="custom-select d-block w-100" id="country" required="">
              <option value="">Choose...</option>
              <option>United Kingdom</option>
            </select>
            <div class="invalid-feedback">
              Please select a valid country.
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="postcode">Postcode</label>
            <input type="text" class="form-control" id="postcode" placeholder="Postcode" required="">
            <div class="invalid-feedback">
              Postcode code required.
            </div>
          </div>
        </div>
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="same-address">
          <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
        </div>
        </form>
        <hr class="mb-4">
        <%= simple_form_for(@order, url: order_path(@order)) do |f| %>
        <div class="form-group">
          <%= f.input :delivery_option, as: :radio_buttons, checked: 'Collect from Seller',
          collection: ['Collect from Seller', 'Standard Free Delivery (3-5 days)', 'Collect from preferred location'] %>
        </div>
        <div class="form-group">
          <%= f.input :payment_option, as: :radio_buttons, checked: 'Cash (if collect from seller)',
          collection: ['Debit card', 'Cash (if collect from seller)', 'Paypal'] %>
        </div>
        <div class="form-group">
          <%= f.input :state, as: :hidden, input_html: { value: "completed" } %>
        </div>
        <hr class="mb-4">
        <h6 style="text-align: center;color:#237480;">⭐️ YOU HAVE ITEM(S) FOR SWAP IN YOUR BASKET ⭐️</h6>
        <br>
        <h6>Please note: in order to swap an item with a seller, you must get in touch with them via chat to confirm your swap and delivery.</h6>
        <div class="mt-3">
          <div class="col-4 offset-4 btn btn-info">
            <a href="https://wa.me/447850390052?text=Please%20contact%20me%20about%20this%20product%20listing" target="blank" class="d-flex flex-row justify-content-between">
              <h5 class="text-center text-white mt-2">CONTACT SELLER</h5>
              <i class="fab fa-whatsapp text-white mt-1" style="font-size: 32px;"></i>
            </a>
          </div>
        </div>
        <br>
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="swap">
          <label style="color:#237480;" class="custom-control-label" for="swap">Swap confirmed with <%= @order.products.first.user.nickname %>? <br> You must check this box in order to complete your swap</label>
        </div>
        <div class="row">
         <div class="col-md-12 mb-6">
          <hr class="mb-4">
           <%= f.button :submit, 'CONFIRM ORDER', class: 'btn btn-block btn-success mb-5 text-white' %>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/orders/confirmation_page.html.erb
<div class="container text-center ">
  <div class="row d-flex justify-content-center">
    <div class="col-12 mt-5 text-center">
      <h1 class="main mb-3">Thank you for your order!</h1>
      <h4>Order ref # <%= @order.id %></h4>
      <h4>Delivered via: <span class="order-option"><%= @order.delivery_option %></span></h4>
      <h4>Paid by: <span class="order-option"><%= @order.payment_option %></span></h4>
      <h4>A confirmation was sent to <%= @order.user.email %></h4>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-8 mt-5 ">
      <h3 class="mb-3"> Order summary: </h3>
      <% @order.product_orders.each do |item| %>
      <div class="d-flex flex-column">
        <div class="card-product border-rounded">
          <% item.product.photos.each_with_index do |photo, index| %>
          <%= cl_image_tag photo.key, height: 200, width: 200, crop: :fill, gravity: :center %>
          <% end %>
          <div class="card-product-infos text-left">
            <h5><%= item.product.name %></h5>
            <p><%= item.product.description %></p>
            <% if item.product.sale_type == "Swap" %>
                <p class="pink-text"><%= item.product.sale_type %></p>
              <% else %>
                <p class="yellow-text">Buy</p>
              <% end %>
            <p>£<%= item.product.price_cents %></p>
          </div>
        </div>
      </div>
      <% end %>
      <hr>
      <h4>Total: £<%= @order.total_price %></h4>
      <%= link_to "Your orders", orders_path, class: "btn btn-primary text-white mb-5" %>
    </div>
  </div>
</div>

app/views/orders/edit.html.erb
<div class="container mb-3 min-vh-100">
  <div class="row">
    <div class="col-md-12 mt-4 text-center">
      <h1>Your basket</h1>
    </div>
  </div>
  <h5>Hi <%= @order.user.name.capitalize %>!</h5>
  <% if @order.product_orders.count == 0 || @order.product_orders.count == 1 %>
  <h5>You have <%= @order.product_orders.count %> item in your basket</h5>
  <% else %>
  <h5>You have <%= @order.product_orders.count %> items in your basket</h5>
<% end %>
  <div class="card-body mt-5">
    <div class="row align-items-center">

      <% @order.product_orders.each do |item| %>
        <div class="col-12 col-sm-12 col-md-3 text-center mb-3">
          <% item.product.photos.each_with_index do |photo, index| %>
            <%= cl_image_tag photo.key, height: 200, width: 200, crop: :fill, gravity: :center %>
          <% end %>
        </div>
        <div class="col-12 col-sm-12 col-md-5 text-sm-center text-md-left ">
          <h5><%= item.product.name %></h5>
          <p><%= item.product.description %></p>
          <% if item.product.sale_type == "Swap" %>
                <p class="pink-text">Sale type: <%= item.product.sale_type %></p>
              <% else %>
                <p class="yellow-text">Sale type: <%= item.product.sale_type %></p>
              <% end %>
        </div>
        <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row justify-content-between">
          <div class="col-3 col-sm-3 col-md-6 text-md-right">

            <h5 class="mt-1" id="price-item">£<%= item.product.price_cents %><span class="text-muted"></span></h5>
          </div>

          <div class="col-2 col-sm-2 col-md-2 text-right">
            <button type="button" id="sweet-alert-demo" class="btn btn-outline-primary btn-xs">
              <i class="fa fa-trash" aria-hidden="true"></i>
            </button>
            <%= link_to product_order_path(item.id), method: :delete, id: "delete-link" do %>
           <% end %>
          </div>
        </div>
        <hr>
      <% end %>
    </div>
    <div class="card-footer d-flex justify-content-between mt-3">
      <% unless current_user.orders.find_by(state:"pending").product_orders.count.zero? %>
      <div>
        <%= link_to 'Checkout', order_checkout_path(@order), class: "btn btn-warning text-white" %>
      </div>
      <span><h5 id="price-total">Total: £<%= @order.total_price %></h5></span>
    </div>

  </div>

  <div class="recommendations">
    <h3 class="align-text ml-2 mb-4 mt-4">You may also like...</h3>
    <div class="cards d-flex flex-wrap justify-content-around position-relative text-center ml-1">
      <% @similar_products.sample(4).each do |product| %>
        <div class="card border-rounded mb-4" style="width: 16rem; height: 28rem;">
          <div class="card-body">
            <%= link_to product_path(product) do %>
              <% product.photos.each_with_index do |photo, index| %>
                <%= cl_image_tag photo.key, height: 200, width: 200, crop: :fill, gravity: :center %>
              <% end %>
            <% end %>

            <%= link_to product_path(product) do%>
              <h5 class="card-title mt-1"><%= product.name.capitalize %></h5>
              <p class="card-text m-0" style="font-size: 14px">Category: <%= product.category %></p>
              <p class="card-text m-0" style="font-size: 14px">Condition: <%= product.condition %></p>
              <p class="card-text m-0" style="font-size: 14px">Sale type: <%= product.sale_type %></p>
              <p class="card-text m-0" style="font-size: 20px">£<%= product.price_cents %></p>
              <% end %>

            <div class="rating text-center position-absolute d-flex flex-row mr-4 mb-3">
              <%=  link_to product_product_orders_path(product), method: :post do%>
                <i class="fas fa-shopping-basket" style="font-size: 20px;"></i>
              <% end %>
              <%= link_to save_item_product_path(product), remote: true, method: :post do %>
                <%= render 'products/like_button', product: product %>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>

    </div>
  </div>
<% end %>
</div>

app/views/orders/index.html.erb
<div class="container">
  <div class="row justify-content-center">

      <h1 class="mt-3">Your Orders</h1>

  </div>
  <div class="row">
    <% @orders.each do |order| %>
    <div class="col mb-3">
      <% if order.state == "completed" %>
      <div class="card shadow-none border-rounded mb-3" style="width: 70rem; height: auto;">
         <div class="card-header bg-transparent">
          <div class="d-flex justify-content-between" style="color:#343a40;">
          <h6>Order date</h6>
          <h6><%= order.updated_at.strftime("%d/%m/%Y") %></h6>
          </div>
          <div class="d-flex justify-content-between" style="color:#343a40;">
            <h6>Order #</h6>
            <h6><%= order.id %></h6>
          </div>
          <div class="d-flex justify-content-between" style="color:#343a40;">
            <h6>Order total: </h6>
            <h6>£<%= order.total_price %> (<%= order.products.count%> items)</h6>
          </div>
          <div class="d-flex justify-content-between" style="color:#343a40;">
            <h6>Paid by:</h6>
            <h6><%= order.payment_option %></h6>
          </div>
          <div class="d-flex justify-content-between" style="color:#343a40;">
            <h6>Shipped by:</h6>
            <h6><%= order.delivery_option %></h6>
          </div>
        </div>
        <div class="card-body">
          <div class="row d-flex flex-wrap">
            <div class="col">
              <h5 style="color:#237480;">SOLD BY: <%= order.products.first.user.nickname %></h5>
              <h5 style="color:#237480;">CONTACT SELLER: <a href="https://wa.me/447731957278?text=Please%20contact%20me%20about%20this%20product%20listing" target="blank"><i class="fab fa-whatsapp"></i></a></h5>
              <% order.products.each do |product_order| %>
              <div class="row mt-3">
                <div class="col-9 mb-3 d-flex align-items-center">
                  <% product_order.photos.each_with_index do |photo, index| %>
                  <%= cl_image_tag photo.key, height: 150, width: 150, crop: :fill, gravity: :center %>
                  <% end %>
                  <div class="pl-3">
                    <p class="my-0"><%= product_order.name %></p>
                    <p class="my-0">Price: £<%= product_order.price_cents %></p>
                    <p class="my-0">Description: <%= product_order.description %></p>
                    <% if product_order.sale_type == "Swap" %>
                      <p class="my-0">Sale Type: <%= product_order.sale_type %></p>
                    <% else %>
                      <p class="my-0">Sale Type: Buy</p>
                    <% end %>
                   <%= link_to "Write a review", new_user_review_path(product_order.user, product:product_order), class: "btn btn-warning text-white mb-1" %>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
   <% end %>
  </div>
  <div class="container">
    <%= link_to "Back to My Account", my_account_path, class: "btn btn-primary text-white mb-3" %>
  </div>
</div>

app/views/orders/my_account.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <div class="d-flex flex-column min-vh-70 mt-5">
        <h1>My Account</h1>
        <%= image_tag "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1647&q=80", class: "avatar-large m-2", alt: "profile" %>
        <h3 class="my-4">Hi <%= current_user.nickname %>!</h3>
        <h4><%= link_to "Your orders", orders_path %></h4>
        <h4><%= link_to "Saved items", saved_items_path %></h4>
        <br/>
        <h4><%= link_to('Logout', destroy_user_session_path, method: :delete) %></h4>
      </div>
    </div>
    <div class="col-8 mt-5">
      <h1 class="mb-3">You might like...</h1>
      <div class="d-flex flex-column">

        <% @featured_products.each do |product| %>
          <div class="card-product border-rounded">
            <%= link_to product_path(product) do %>
              <% product.photos.each_with_index do |photo, index| %>
                <%= cl_image_tag photo.key, height: 200, width: 200, crop: :fill, gravity: :center %>
              <% end %>
            <% end %>
            <div class="card-product-infos">
              <h2 class="text-dark"><%= product.name %></h2>
              <p><%= product.description %></p>
              <% if product.sale_type == "Swap" %>
                <p class="pink-text"><%= product.sale_type %></p>
              <% else %>
                <p class="yellow-text"><%= product.sale_type %></p>
              <% end %>
              <% if product.price_cents > 0 %>
                <p>£<%= product.price_cents %></p>
              <% end %>
              <p>Seller: <%= product.user.nickname %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/sale_items.html.erb
<div class="container my-3">
  <div class="row">
    <div class="col">
      <h1 class="text-center">Your sale items</h1>
      <h3 class="mb-5 text-center">View or edit your items for sale</h3>
        <div class="sale_items">
          <div class="cards d-flex text-center ml-1">
            <% @user.products.each do |product| %>
              <div class="card border-rounded mb-4 ml-4" style="width: 16rem; height: 28rem;">
                <div class="card-body">
                  <%= link_to product_path(product) do %>
                    <% product.photos.each_with_index do |photo, index| %>
                      <%= cl_image_tag photo.key, height: 200, width: 200, crop: :fill, gravity: :center %>
                    <% end %>
                  <% end %>
                    <h5 class="card-title mt-1"><%= product.name.capitalize %></h5>
                    <p class="card-text m-0" style="font-size: 14px">Category: <%= product.category %></p>
                    <p class="card-text m-0" style="font-size: 14px">Condition: <%= product.condition %></p>
                    <% if product.sale_type == "Swap" %>
                      <p class="card-text m-0 pink-text" style="font-size: 14px">Sale type: <%= product.sale_type %></p>
                    <% else %>
                      <p class="card-text m-0 yellow-text" style="font-size: 14px">Sale type: <%= product.sale_type %></p>
                    <% end %>
                    <p class="card-text m-0" style="font-size: 14px">Sale type: <%= product.sale_type %></p>
                    <p class="card-text m-0" style="font-size: 14px">Seller: <%= product.user.nickname %></p>
                    <% if product.price_cents > 0 %>
                      <p class="card-text m-0 mb-3" style="font-size: 20px">£<%= product.price_cents %></p>
                    <% end %>
                    <p>
                      <%= link_to edit_product_path(product) do %>
                      <i class="fas fa-edit" style="font-size: 24px;"></i>
                      <% end %>
                    </p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <%= link_to "Back", request.referer.present? ? request.referer : default_path, class: "btn btn-success text-white" %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<h1>Your Order</h1>

<table>
  <tr>
    <th>Customer</th>
    <td><%= @order.user %></td>
  </tr>
  <tr>
    <th>Status:</th>
    <td><%= @order.status %></td>
  </tr>
  <tr>
    <th>Items:</th>
    <td><%= @order.product_orders.count %></td>
  </tr>
  <tr>
    <th>Items</th>
    <th>Title</th>
    <th>Quantity</th>
    <th>Unit Price</th>
    <th>Subtotal</th>
  </tr>
  <tr>
  <% @order.product_orders.each do |item| %>
  <td> cl_image_tag </td>
    <td><strong>Name: </strong><%= item.product.name %></td>
    <td><strong>Category: </strong><%= item.product.category %></td>
    <td><strong>Description: </strong><%= item.product.description %></td>
    <td><strong>Price: </strong>£<%= item.product.price %></td>
    <td><strong>Location: </strong><%= item.product.location%></td>
<% end %>
 </tr>
</table>