config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#home'

  resources :products do
    resources :product_orders, only: [ :create, :destroy ]
    member do
      post 'save_item', to: 'products#save_item'
    end
  end

  resources :orders, only: [ :index, :show, :edit, :update, :destroy ] do
    get 'basket', to: 'orders#basket'
    get 'checkout', to: 'orders#checkout'
    get 'confirmation_page', to: 'orders#confirmation_page'
  end

  resources :product_orders, only: [:destroy]

  get 'my_account', to: 'orders#my_account'
  get 'reviews', to: 'orders#reviews'
  get 'sale_items', to: 'orders#sale_items'
  get 'saved_items', to: 'products#saved_items'

  resources :users, only: [ :show ] do
    resources :reviews, only: [ :new, :create, :show ]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user

  include PgSearch::Model
  pg_search_scope :search_by_product,
                  against: [ :name, :description, :address, :category, :sale_type],
                  using: {
                    tsearch: { prefix: true }
                  }

  DELIVERY_OPTIONS = ["Collect from chosen location", "Deliver Home", "Arrange pick-up"]
  PAYMENT_OPTIONS = ["Card Payment", "Cash Payment"]
  SALE_TYPE = ["Sell", "Swap"]

  acts_as_favoritable

  has_many :product_orders, dependent: :destroy
  has_many :orders, through: :product_orders, dependent: :destroy
  has_many :users, through: :orders
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :address, presence: true
  validates :colour, presence: true
  validates :condition, presence: true
  validates :size, presence: true
  validates :sale_type, presence: true, inclusion: { in: SALE_TYPE }
  # validates :payment_options, inclusion: { in: PAYMENT_OPTIONS }
  # validates :deliver_option, inclusion: { in: DELIVERY_OPTIONS }
  monetize :price_cents
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index, :show, :filter]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def home
    @products = policy_scope(Product)
    @products = Product.where.not(latitude: nil, longitude: nil)
    @markers = @products.geocoded.map do |product|
      {
        lat: product.latitude,
        lng: product.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { product: product })
      }
    end
    @featured_products = @products.all.sample(8)
  end

  def index
    if params[:query].present?
    @products = Product.search_by_product(params[:query]).page(params[:page])
    else
    @products = Product.page(params[:page])
    end
  end

  def show
    @product_orders = ProductOrder.new
    @user = current_user
    @order = Order.new
  end

  def new
    @product = Product.new
    authorize @product
  end

  def edit; end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    authorize @product
    if @product.save!
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def save_item
    @product = Product.find(params[:id])
    current_user.favorited?(@product) ? current_user.unfavorite(@product) : current_user.favorite(@product)
  end

  def saved_items
    @favorite_products = current_user.favorited_by_type('Product')
  end

  def update
    @product.update(product_params)
    if @product.save
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to product_path
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :address,
      :category,
      :colour,
      :condition,
      :size,
      :price_cents,
      :sale_type,
      # :payment_options,
      # :deliver_option,
      photos: []
    )
  end

  def set_product
    @product = Product.find(params[:id])
    authorize @product
  end
end

app/views/products/_info_window.html.erb
<div class="card-trip">
  <br>
  <%= link_to product_path(product) do %>
    <% product.photos.each_with_index do |photo, index| %>
      <%= cl_image_tag photo.key, height: 110, width: 110, crop: :fill, gravity: :center %>
    <% end %>
  <% end %>
  <a href= "<%= product_path(product) %>">
  <h5><%= product.name %></h5>
</div>

app/views/products/_like_button.html.erb
<% if user_signed_in? %>
  <div class="like-icon mx-2 <%= 'red' if current_user.favorited?(product) %>" data-id="<%= product.id %>">
    <i class="fas fa-heart" style="font-size: 20px;"></i>
  </div>
<% end %>

app/views/products/_map_box.html.erb
<h1><%= product.name %></h1>

app/views/products/_product.html.erb
  <div class="card border-rounded mx-1 mb-4" style="width: 16rem; height: 28rem;">
    <div class="card-body">
      <%= link_to product_path(product) do %>
        <% product.photos.each_with_index do |photo, index| %>
          <%= cl_image_tag photo.key, height: 200, width: 200, crop: :fill, gravity: :center %>
        <% end %>
      <% end %>
      <h5 class="card-title mt-1 text-dark"><%= product.name.capitalize %></h5>
      <p class="card-text m-0" style="font-size: 14px">Category: <%= product.category %></p>
      <p class="card-text m-0" style="font-size: 14px">Condition: <%= product.condition %></p>
      <% if product.sale_type == "Swap" %>
        <p class="card-text m-0 pink-text" style="font-size: 14px">Sale type: <%= product.sale_type %></p>
      <% else %>
        <p class="card-text m-0 yellow-text" style="font-size: 14px">Sale type: Buy </p>
      <% end %>
      <p class="card-text m-0" style="font-size: 14px">Sale type: <%= product.sale_type %></p>
      <p class="card-text m-0" style="font-size: 20px">£<%= product.price_cents %></p>
      <div class="rating text-center position-absolute">
        <%= link_to save_item_product_path(product), remote: true, method: :post do %>
          <%= render 'products/like_button', product: product %>
        <% end %>
      </div>
    </div>
  </div>

app/views/products/edit.html.erb
<div class="container m-3">
  <div class="row">
    <div class="col-6 offset-3">
      <h2>Edit product:</h2>
      <%= simple_form_for @product do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :category, collection: ["Boys-clothing", "Girls-clothing", "Playtime", "Nursery-furniture", "Pushchairs"] %>
        <%= f.input :colour %>
        <%= f.input :address %>
        <%= f.input :condition %>
        <%= f.input :size %>
        <%= f.input :sale_type, as: :radio_buttons, collection: ["Sell", "Swap"] %>
        <%= f.input :price_cents, label: 'Price' %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit class: "btn btn-primary mt-2 text-white" %>
      <% end %>
      <%= link_to 'Back', products_path, class: "btn btn-primary mt-2 text-white" %>
    </div>
  </div>
</div>

app/views/products/home.html.erb
<div class="container">
    <div class="d-flex justify-content-center">
      <div class="d-flex flex-row mt-3 mb-2">
        <h5 class="mx-3"><%= link_to "Toys", products_path(query: "Playtime"), class: "category-links" %></h5>
        <h5 class="mx-3"><%= link_to "Boys Clothing", products_path(query: "Boys-clothing"), class: "category-links" %></h5>
        <h5 class="mx-3"><%= link_to "Girls Clothing", products_path(query: "Girls-clothing"), class: "category-links" %></h5>
        <h5 class="mx-3"><%= link_to "Nursery", products_path(query: "Nursery"), class: "category-links" %></h5>
        <h5 class="mx-3"><%= link_to "Pushchairs", products_path(query: "Pushchairs"), class: "category-links" %></h5>
      </div>
    </div>
    <div class="center">
      <h2 class="item-1 position-absolute d-block">⭐️ Find excellent quality pre-loved items for your baby ⭐️</h2>
      <h2 class="item-2 position-absolute d-block">⭐️ Sell unused clothes and make some money ⭐️</h2>
      <h2 class="item-3 position-absolute d-block">⭐️ Support your local parent community ⭐️</h2>
    </div>
    <div id="buybaby" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#buybaby" data-slide-to="0" class="active"></li>
        <li data-target="#buybaby" data-slide-to="1"></li>
        <li data-target="#buybaby" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= image_tag("carousel_1.jpg", class: "d-block carousel-img" )%>
            <div class="carousel-caption text-left">
              <h1 class="carousel-heading caption-1">New arrivals</h1>
              <p class="caption-1" style="font-size: 20px;">Check out our new finds this week!</p>
              <p>
                <%= link_to "View all products", products_path, class: "btn btn-warning text-white"%>
              </p>
            </div>
        </div>
        <div class="carousel-item">
          <%= image_tag("carousel_2.jpg", class: "d-block carousel-img" )%>
             <div class="carousel-caption text-left">
                <h1 class="carousel-heading caption-2">Find a bargain</h1>
                <p class="caption-2" style="font-size: 20px;">Search for bargains that you'll love for your little one</p>
                <p>
                  <%= link_to "Buy a product", products_path(query: "sell"), class: "btn btn-danger text-white"%>
                </p>
             </div>
        </div>
        <div class="carousel-item">
          <%= image_tag("carousel_3.jpg", class: "d-block carousel-img" )%>
             <div class="carousel-caption text-left">
                <h1 class="carousel-heading caption-3">Swap & save</h1>
                <p class="caption-3" style="font-size: 20px;">Preloved items you don't want to miss!</p>
                <p>
                   <%= link_to "View all swap items", products_path(query: "swap"), class: "btn btn-success text-white"%>
                </p>
             </div>
        </div>
        <a class="carousel-control-prev" href="#buybaby" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#buybaby" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <div class="divider my-3" style="display: flex;">
      <hr style="width:50%; text-align:left; margin-left:0;margin-right:0;margin-top: 40px;height:2px;border-width:0;color:#FFDA1F;background-color:#FFDA1F">
        <%= image_tag("logo.png", width: "90px", height: "90px", class: "logo" )%>
      <hr style="width:50%; text-align:left; margin-left:0;margin-right:0;margin-top: 40px;height:2px;border-width:0;color:#FFDA1F;background-color:#FFDA1F">
    </div>
    <div class="about text-center">
      <div class="d-flex flex-row justify-content-center">
        <h1 style="font-size: 56px;">Buy</h1>
        <h1 style="color: #9CF6F6;font-size: 56px;">Ba</h1>
        <h1 style="color: #FFE357;font-size: 56px;">by</h1>
      </div>
      <h3 class="text-dark mt-2">A place for parents to shop and swap locally</h3>
      <div class="mt-5">
        <h6 class="text-dark">Search and browse over 100s pre-loved baby, toddler, and maternity items to buy</h6>
        <h6 class="text-dark">Or explore items available to swap with other parents nearby</h6>
      </div>
      <div class="mt-5">
        <h4 class="text-dark">How it works:</h4>
      </div>
      <div class="d-flex flex-row justify-content-around">
        <%= image_tag "free.png", alt: "free" %>
        <%= image_tag "list.png", alt: "list" %>
        <%= image_tag "money.png", alt: "money" %>
      </div>
      <div class="d-flex flex-row justify-content-around">
        <div class="w-25"><p>Advertise your items for free on BuyBaby</p></div>
        <div class="w-25"><p>Connect with other parents locally to swap or sell your item</p></div>
        <div class="w-25"><p>Earn money from selling old items or save by swapping!</p></div>
      </div>
    </div>
    <div class="category-headings">
      <hr style="width:100%; text-align:left; margin-left:0;margin-right:0;margin-top: 40px;height:2px;border-width:0;color:#FFDA1F;background-color:#FFDA1F">
      <h1 class="text-dark text-center my-5">Explore our categories</h1>
      <div class="row justify-content-center">
        <div class="col-md-4">
          <div class="divider" style="margin: 0 auto">
            <h3 class="mx-2 my-3">Toys</h3>
          </div>
        </div>
        <div class="col-md-4">
          <div class="divider" style="margin: 0 auto">
            <h3 class="mx-2 my-3">Nursery</h3>
          </div>
        </div>
        <div class="col-md-4">
          <div class="divider" style="margin: 0 auto">
            <h3 class="mx-2 my-3">Pushchairs</h3>
          </div>
        </div>
      </div>
    </div>
    <div class="category-cards d-flex flex-row justify-content-center">
      <div class="card text-white mx-2" style="height:16rem; width:60rem;">
        <%= image_tag('toys.jpg', class: 'card-img', alt: 'Card image')%>
        <%= link_to products_path(query: "Playtime"), class: "card-img-overlay" do %>
          <h5 class="card-title category-card-title">Toys</h5>
          <p class="card-text category-text">Playtime & Fun</p>
        <% end %>
      </div>
      <div class="card text-white mx-2" style="height:16rem; width:60rem;">
        <%= image_tag('nursery1.jpeg', class: 'card-img', alt: "Card image") %>
        <%= link_to products_path(query: "Nursery"), class: "card-img-overlay" do %>
          <h5 class="card-title category-card-title">Nursery</h5>
          <p class="card-text category-text">For your home</p>
        <% end %>
      </div>
      <div class="card text-white mx-2" style="height:16rem; width:60rem;">
        <%= image_tag('pushchair_forest.jpg', class: 'card-img', alt: "Card image") %>
        <%= link_to products_path(query: "Pushchairs"), class: "card-img-overlay" do %>
          <h5 class="card-title category-card-title">Pushchair</h5>
          <p class="card-text category-text">Enjoy the outdoors</p>
        <% end %>
      </div>
    </div>
    <div class="category-headings">
      <div class="row justify-content-center">
        <div class="col-md-4">
          <div class="divider" style="margin: 0 auto">
            <h3 class="mx-2 my-3">Sale</h3>
          </div>
        </div>
        <div class="col-md-4">
          <div class="divider" style="margin: 0 auto">
            <h3 class="mx-2 my-3">New In</h3>
          </div>
        </div>
        <div class="col-md-4">
          <div class="divider" style="margin: 0 auto">
            <h3 class="mx-2 my-3">Swap</h3>
          </div>
        </div>
      </div>
    </div>
    <div class="category-cards d-flex flex-row justify-content-center">
      <div class="card text-white mx-2" style="height:16rem; width:60rem;">
        <%= image_tag('sale.jpg', class: 'card-img', alt: 'Card image')%>
        <%= link_to products_path(query: "sell"), class: "card-img-overlay" do %>
          <h5 class="card-title category-card-title">Sale</h5>
          <p class="card-text category-text">Up to 50% off</p>
        <% end %>
      </div>
      <div class="card text-white mx-2" style="height:16rem; width:60rem;">
        <%= image_tag('new arrivals.jpg', class: 'card-img', alt: "Card image") %>
        <%= link_to products_path, class: "card-img-overlay" do %>
          <h5 class="card-title category-card-title">New arrivals</h5>
          <p class="card-text category-text">Discover more</p>
        <% end %>
      </div>
      <div class="card text-white mx-2" style="height:16rem; width:60rem;">
        <%= image_tag('swap.jpg', class: 'card-img', alt: "Card image") %>
        <%= link_to products_path(query: "swap"), class: "card-img-overlay" do %>
          <h5 class="card-title category-card-title">Swap</h5>
          <p class="card-text category-text">Preloved items</p>
        <% end %>
      </div>
    </div>
    <div class="my-5">
      <hr style="width:100%;text-align:left;margin-left:0;margin-right:0;margin-top: 15px;height:2px;border-width:0;color:#FFDA1F;background-color:#FFDA1F">
      <h1 class="title text-center text-dark my-5">Search local items near you</h1>
    </div>
    <div class= "position-relative"
      id="map"
      style="width: 100%; height: 500px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <div class="my-5">
      <hr style="width:100%;text-align:left;margin-left:0;margin-right:0;margin-top: 15px;height:2px;border-width:0;color:#FFDA1F;background-color:#FFDA1F">
      <h1 class="title text-center text-dark my-5">Featured Items</h1>
    </div>
     <div class="cards d-flex flex-wrap justify-content-center">
      <% @featured_products.each do |product| %>
        <div class="card border-rounded mb-4 mx-1" style="width: 16rem; height: 28rem;">
          <div class="card-body text-center">
            <%= link_to product_path(product) do %>
              <% product.photos.each_with_index do |photo, index| %>
                <%= cl_image_tag photo.key, height: 200, width: 200, crop: :fill, gravity: :center %>
              <% end %>
            <% end %>
            <%= link_to product_path(product) do%>
              <h5 class="card-title mt-1"><%= product.name.capitalize %></h5>
              <p class="card-text m-0" style="font-size: 14px">Category: <%= product.category %></p>
              <p class="card-text m-0" style="font-size: 14px">Condition: <%= product.condition %></p>
              <% if product.sale_type == "Swap" %>
                <p class="card-text m-0 pink-text" style="font-size: 14px">Sale type: <%= product.sale_type %></p>
              <% else %>
                <p class="card-text m-0 yellow-text" style="font-size: 14px">Sale type: Buy</p>
              <% end %>
              <% if product.price_cents > 0 %>
                <p class="card-text m-0" style="font-size: 20px">£<%= product.price_cents %></p>
              <% end %>
            <% end %>
            <div class="rating text-center position-absolute">
              <%= link_to save_item_product_path(product), remote: true, method: :post do %>
                <%= render 'products/like_button', product: product %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="m-3">
    <div class="text-center" style="margin-top: 50px;">
      <h1>Products</h1>
      <h5>View the latest products on offer!</h5>

      <div class="d-flex justify-content-center">
        <div class="d-flex flex-row mt-3 mb-2">
          <h5 class="mx-3"><%= link_to "Toys", products_path(query: "Playtime"), class: "category-links  text-success" %></h5>
          <h5 class="mx-3"><%= link_to "Boys Clothing", products_path(query: "Boys-clothing"), class: "category-links  text-success" %></h5>
          <h5 class="mx-3"><%= link_to "Girls Clothing", products_path(query: "Girls-clothing"), class: "category-links  text-success" %></h5>
          <h5 class="mx-3"><%= link_to "Nursery", products_path(query: "Nursery"), class: "category-links  text-success" %></h5>
          <h5 class="mx-3"><%= link_to "Pushchairs", products_path(query: "Pushchairs"), class: "category-links  text-success" %></h5>
        </div>
      </div>

      <div class="d-flex justify-content-center">
        <div class="d-flex flex-row mt-3 mb-2">
          <h5 class="mx-3"><%= link_to "Items for swap", products_path(query: "swap"), class: "category-links text-info" %></h5>
          <h5 class="mx-3"><%= link_to "Items for sale", products_path(query: "sell"), class: "category-links text-info" %></h5>
        </div>
      </div>

    </div>
  </div>

  <div>
    <p><%= @products.total_count %> results</p>
  </div>
    <div class="cards d-flex flex-wrap position-relative text-center ml-1">
      <% @products.each do |product| %>
        <div class="card border-rounded mb-4 mx-1" style="width: 16rem; height: 28rem;">
          <div class="card-body">
            <%= link_to product_path(product) do %>
              <% product.photos.each_with_index do |photo, index| %>
                <%= cl_image_tag photo.key, height: 200, width: 200, crop: :fill, gravity: :center %>
              <% end %>

            <% end %>
              <h5 class="card-title text-dark mt-1"><%= product.name.capitalize %></h5>
              <p class="card-text m-0" style="font-size: 14px"><%= product.category %></p>
              <p class="card-text m-0" style="font-size: 14px"><%= product.condition %></p>
              <% if product.sale_type == "Swap" %>
                <p class="card-text m-0 pink-text" style="font-size: 14px"><%= product.sale_type %></p>
              <% else %>
                <p class="card-text m-0 yellow-text" style="font-size: 14px">Buy</p>
              <% end %>
              <% if product.price_cents > 0 %>
                <p class="card-text m-0" style="font-size: 20px">£<%= product.price_cents %></p>
              <% end %>
            <div class="rating text-center position-absolute">
              <%= link_to save_item_product_path(product), remote: true, method: :post do %>
                <%= render 'products/like_button', product: product %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-end">
      <%= paginate @products %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container m-3">
  <div class="row">
    <div class="col-6 offset-3">
      <h1 class="mb-5 text-center">Sell or swap an item!</h1>
      <h2>Add new product:</h2>
      <%= simple_form_for @product do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :category, collection: ["Boys-clothing", "Girls-clothing", "Playtime", "Nursery-furniture", "Pushchairs"] %>
        <%= f.input :colour %>
        <%= f.input :address %>
        <%= f.input :condition %>
        <%= f.input :size %>
        <%= f.input :price_cents, label: 'Price' %>
        <%= f.input :sale_type, as: :radio_buttons, collection: ["Sell", "Swap"] %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit class: "btn btn-primary mt-2 text-white" %>
      <% end %>
      <%= link_to 'Back', products_path, class: "btn btn-primary mt-2 text-white" %>
    </div>
  </div>
</div>

app/views/products/save_item.js.erb
var productId = '<%= @product.id%>'

function toggleLikeButton(productId, innerHTML) {
  let likeButton = document.querySelector(`.like-icon[data-id='${productId}']`)
  likeButton.classList.toggle('red');
}

toggleLikeButton(productId, '<%= j render "products/product", product: @product %>');

app/views/products/saved_items.html.erb
<div class="container my-3">
  <div class="row">
    <div class="col">
      <h1 class="mb-5 text-center">Saved Items</h1>
        <div class="favorites">
          <div class="cards d-flex flex-wrap position-relative text-center">
          <% @favorite_products.each do |product| %>
            <%= render 'product', product: product %>
          <% end %>
        </div>
      </div>
      <%= link_to "Back", request.referer.present? ? request.referer : default_path, class: "btn btn-danger text-white" %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container mt-5 d-flex">
  <div class="row">
    <div class="col">
      <% @product.photos.each_with_index do |photo, index| %>
        <div class="position-relative">
          <%= cl_image_tag photo.key, height: 500, width: 500, crop: :fill, gravity: :center %>
        </div>
        <div class="show-rating position-absolute">
          <%= link_to save_item_product_path(@product), remote: true, method: :post do %>
            <div class="row pl-2">
              <%= render 'products/like_button', product: @product %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-6">
    <div class="ml-3">
      <h1><%= @product.name.capitalize %></h1>
      <p><%= link_to 'Add to basket', product_product_orders_path(@product), method: :post, class: "btn btn-primary text-white my-3" %></p>
      <table class="mt-3" style="width:100%">
        <tr>
          <th><h5 class="text-dark" class="text-dark">Category:</h5></th>
          <td><h5 class="text-dark"><%= @product.category.capitalize %></h5></td>
        </tr>
        <tr>
          <th><h5 class="text-dark">Description:</h5></th>
          <td><h5 class="text-dark"><%= @product.description.capitalize %></h5></td>
        </tr>
        <tr>
          <th><h5 class="text-dark">Condition:</h5></th>
          <td><h5 class="text-dark"><%= @product.condition.capitalize %></h5></td>
        </tr>
        <tr>
          <th><h5 class="text-dark">Sale type:</h5></th>
          <% if @product.sale_type == "Swap" %>
            <td><h5 class="text-dark"><%= @product.sale_type %></h5></td>
          <% else %>
            <td><h5 class="text-dark">Buy</h5></td>
          <% end %>
        </tr>
        <tr>
          <th><h5 class="text-dark">Size:</h5></th>
          <td><h5 class="text-dark"><%= @product.size.capitalize %></h5></td>
        </tr>
        <tr>
          <th><h5 class="text-dark">Colour:</h5></th>
          <td><h5 class="text-dark"><%= @product.colour.capitalize %></h5></td>
        </tr>
        <% if @product.price_cents > 0 %>
          <tr>
            <th><h5 class="text-dark">Price:</h5></th>
            <td><h5 class="text-dark">£<%= @product.price_cents %></h5></td>
          </tr>
        <% end %>
        <tr>
          <th><h5 class="text-dark">Seller:</h5></th>
          <td><h5 class="text-dark"><%= @product.user.nickname %></h5></td>
        </tr>
      </table>
      <br/>
      <div class="links list-inline">
        <% if @product.user == current_user %>
          <p><%= link_to 'Edit item', edit_product_path(@product), class: "btn btn-outline-primary ask" %></p>
        <% end %>
      </div>
      <br/>
      <p><i class="fas fa-shield-alt"></i> Be covered by BuyBaby's Buyer Protection, which includes our refund policy</p>
    </div>
  </div>
</div>

<div class="container">
  <div class="seller-info">
    <%= image_tag("sandy.jpeg", class: "avatar", alt: "avatar")%>
    <h5 style="display: inline; margin-left: 10px"> <%= @product.user.nickname %></h5>
    <div class="col-2 d-flex justify-content-end">
      <% total_ratings = [] %>
      <% @product.user.reviews.each do |review| %>
        <% total_ratings << review.rating %>
      <% end %>
      <% if total_ratings == [] %>
          <% 5.times do %>
            <span><i class="far fa-star"></i></span>
          <% end %>
      <% else %>
        <% average_rating = total_ratings.sum / total_ratings.size %>
        <div class="ratings">
          <% average_rating.times do  %>
            <span><i class="fas fa-star"></i></span>
          <% end %>
          <% (5 - average_rating).times do %>
            <span><i class="far fa-star"></i></span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="links my-3">
    <%= link_to "View all seller reviews", user_review_path(@product.user, product:@product), class: "btn btn-primary text-white mb-1" %>
  </div>
</div>